#!/bin/bash

#
#*****************************************************************************
#   Copyright (C) 2012 Thierry Monteil <sage-debian-live!lma.metelu.net>
#   Emil Widmann
#  Distributed under the terms of the GNU General Public License (GPL)
#  as published by the Free Software Foundation; either version 2 of
#  the License, or (at your option) any later version.
#                  http://www.gnu.org/licenses/
#*****************************************************************************
#
# This configuration script allows you to customize your own Sage Debian Live.
# This should contain all customizable variables. Some variables ca be
# overwritten with a custom config file.



### Default language and keyborad of the USB key
BOOT_LOCALE='en_US.UTF-8' ;
BOOT_KEYBOARD='us'



### Image, architecture and distribution
IMAGE='hdd'
ARCHITECTURE='i386'
DISTRO='wheezy'
## The 486 flavour is needed for the installer on i386 architecture.
# LINUX_FLAVOURS='686-pae 486'
LINUX_FLAVOURS='686-pae'
RECOMMENDS='true'
INDICES='true'
COMPRESS='gzip'

DEBIAN_VERSION="${DISTRO}"
LIVE_VERSION="$(lb --version)"
BUILD_DATE="$(date --rfc-3339=date)"
## This must begin with "${BUILD_DATE} "
BUILD_VERSION="${BUILD_DATE} ${DEBIAN_VERSION} ${LIVE_VERSION}"
LONG_NAME="Debian ${DEBIAN_VERSION} Live ${LIVE_VERSION} ${BUILD_DATE} ${BOOT_LOCALE}"
IMG_NAME="${BUILD_DATE}-debian-${DEBIAN_VERSION}-live-${LIVE_VERSION}-${BOOT_KEYBOARD}.img"



### MODULES ###
## Here you can select which modules you want to be installed on the USB key.
MODULES='xfce4 wireless packages'

## If the NON_FREE_WIRELESS variable is set to '1', the non free packages
## needed to let some wireless card work will be added. If set to '0', you live
## USB key will only use free software.
NON_FREE_WIRELESS='1'

### BUILD
## BUILD_DIR is the directory where binary key will be built. It should be on a
## partition with enough free space. This directory will be erased at each
## build.
BUILD_DIR=${BASE_DIR}'/build'


## LOCAL_REPOSITORY is the name of the repository where most stuff will be
## downloaded from.
## You can/should use apt-cacher to save bandwidth:
LOCAL_REPOSITORY='http://localhost:3142/http.debian.net/debian/'
## If apt-cacher is on another machine named my_local_computer on the LAN, you
## can do:
# LOCAL_REPOSITORY='http://my_local_computer:3142/http.debian.net/debian/'
## If apt-cacher is not installed, you can set LOCAL_REPOSITORY to a public
## repository:
# LOCAL_REPOSITORY='http://http.debian.net/debian/'


## BINARY_REPOSITORY is where the Live USB key will download packages from.
## You should set it to a public repository.
BINARY_REPOSITORY='http://http.debian.net/debian/'
## Use apt-cacher here only if you need to build the key without any network
## connection. In such a case, you can also set the 'expire_hours' variable of
## '/etc/apt-cacher/apt-cacher.conf to some nonzero number.
# BINARY_REPOSITORY='http://localhost:3142/http.debian.net/debian/'
# BINARY_REPOSITORY='http://my_local_computer:3142/http.debian.net/debian/'

