#!/bin/bash

#
#*****************************************************************************
#   Copyright (C) 2012 Thierry Monteil <sage-debian-live!lma.metelu.net>
#   2014 adapted by emil.widmann!gmail.com
#  Distributed under the terms of the GNU General Public License (GPL)
#  as published by the Free Software Foundation; either version 2 of
#  the License, or (at your option) any later version.
#                  http://www.gnu.org/licenses/
#*****************************************************************************
#
# This is the configuration script for the small CD images.


IMAGE='iso-hybrid'
RECOMMENDS='false'

MODULES='icewm wireless keepinstall'
